# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.17.0

    working_directory: ~/repo/client

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lintTs
      - run: yarn lintEs
      # - run: yarn test
      # - run: yarn test:coverage

  deployProd:
    branches:
      only:
        - master
    docker:
      - image: google/cloud-sdk

    environment:
      - API_MAILCHIMP
      - EMAIL_TO_1
      - EMAIL_TO_2
      - EMAIL_TO_3
      - EMAIL_TO_4
      - GOOGLE_ACCOUNT
      - GOOGLE_PASSWORD

    steps:
      - run: |
          gcloud config set project $PROJECTPROD
          'gcloud compute ssh' --zone $ZONE $MACHINE -- 'cd /home/cva && docker build -t cva . && docker restart cva'
          gcloud compute url-maps invalidate-cdn-cache $PROJECTPROD --host www.creatingvalue.co --path "/*" --async
